const words = [
    { japanese: "後輩", transcription: { ru: "Кохай", ge: "კოჰაი" }, translation: { ru: "Младший", ge: "უმცროსი" }, image: "images/kohai.jpg" },
    { japanese: "先輩", transcription: { ru: "Сэмпай", ge: "სემფაი" }, translation: { ru: "Старший (ученик, инструктор)", ge: "უფროსი" }, image: "images/sempai.jpg" },
    { japanese: "先生", transcription: { ru: "Сэнсэй", ge: "სენსეი" }, translation: { ru: "Учитель (мастер)", ge: "მასწავლებელი" }, image: "images/sensei.jpg" },
    { japanese: "師範", transcription: { ru: "Шихан", ge: "შიჰანი" }, translation: { ru: "Мастер с 5-7 даном", ge: "ოსტატი" }, image: "images/shihan.jpg" },
    { japanese: "範士", transcription: { ru: "Ханси", ge: "ჰანსი" }, translation: { ru: "Мастер с 8-9 даном", ge: "დიდი ოსტატი" }, image: "images/hanshi.jpg" },
    { japanese: "館長", transcription: { ru: "Кантё (Канчо)", ge: "კანჩო" }, translation: { ru: "Мастер-наставник", ge: "მთავარი მენტორი" }, image: "images/kancho.jpg" },
    { japanese: "総裁", transcription: { ru: "Сосай", ge: "სოსაი" }, translation: { ru: "Шеф, директор", ge: "დირექტორი" }, image: "images/sosai.jpg" },
    { japanese: "組手", transcription: { ru: "Кумитэ", ge: "კუმიტე" }, translation: { ru: "Спарринг", ge: "სპარინგი" }, image: "images/kumite.jpg" },
    { japanese: "一本組手", transcription: { ru: "Иппон-кумитэ", ge: "იპონ-კუმიტე" }, translation: { ru: "Учебный спарринг на один шаг", ge: "სასწავლო სპარინგი ერთი ნაბიჯით" }, image: "images/ippon-kumite.jpg" },
    { japanese: "三本組手", transcription: { ru: "Санбон-кумитэ", ge: "სანბონ-კუმიტე" }, translation: { ru: "Учебный спарринг на три шага", ge: "სასწავლო სპარინგი სამი ნაბიჯით" }, image: "images/sanbon-kumite.jpg" },
    { japanese: "道場", transcription: { ru: "Додзё", ge: "დოჯო" }, translation: { ru: "Тренировочный зал", ge: "სავარჯიშო დარბაზი" }, image: "images/dojo.jpg" },
    { japanese: "型", transcription: { ru: "Ката", ge: "კატა" }, translation: { ru: "Технический комплекс", ge: "ტექნიკური კომპლექსი" }, image: "images/kata.jpg" },
    { japanese: "気合", transcription: { ru: "Киай", ge: "კიაი" }, translation: { ru: "Крик при ударе", ge: "ყვირილი დარტყმისას" }, image: "images/kiai.jpg" },
    { japanese: "基本", transcription: { ru: "Кихон", ge: "კიჰონი" }, translation: { ru: "Базовая техника", ge: "ძირითადი ტექნიკა" }, image: "images/kihon.jpg" },
    { japanese: "押忍", transcription: { ru: "Ос", ge: "ოს" }, translation: { ru: "Приветствие, готовность", ge: "მისალმება" }, image: "images/os.jpg" },
    { japanese: "帯", transcription: { ru: "Оби", ge: "ობი" }, translation: { ru: "Пояс", ge: "ქამარი" }, image: "images/obi.jpg" },
    { japanese: "礼", transcription: { ru: "Рэй", ge: "რეი" }, translation: { ru: "Поклон", ge: "მშვილდოსნობა" }, image: "images/rei.jpg" },
    { japanese: "道", transcription: { ru: "До", ge: "დო" }, translation: { ru: "Путь", ge: "გზა" }, image: "images/do.jpg" },
    { japanese: "武道", transcription: { ru: "Будо", ge: "ბუდო" }, translation: { ru: "Путь воина", ge: "მეომრის გზა" }, image: "images/budo.jpg" },
    { japanese: "移動稽古", transcription: { ru: "Идо-гейко", ge: "იდო-გეიკო" }, translation: { ru: "Основы перемещений", ge: "გადაადგილების საფუძვლები" }, image: "images/ido-geiko.jpg" },
    { japanese: "回転", transcription: { ru: "Кайтэн", ge: "კაიტენი" }, translation: { ru: "Перемещение вращением", ge: "ბრუნვით გადაადგილება" }, image: "images/kaiten.jpg" },
    { japanese: "決め", transcription: { ru: "Кимэ", ge: "კიმე" }, translation: { ru: "Концентрация", ge: "კონცენტრაცია" }, image: "images/kime.jpg" },
    { japanese: "連絡", transcription: { ru: "Ренраку", ge: "რენრაკუ" }, translation: { ru: "Комбинации", ge: "კომბინაციები" }, image: "images/renraku.jpg" },
    { japanese: "自由組手", transcription: { ru: "Дзию кумитэ", ge: "ძიუ კუმიტე" }, translation: { ru: "Свободный спарринг", ge: "თავისუფალი სპარინგი" }, image: "images/jiyu-kumite.jpg" },
    { japanese: "約束一本組手", transcription: { ru: "Якусоку иппон кумитэ", ge: "იაკუსოკუ იპონ კუმიტე" }, translation: { ru: "Условный спарринг на один шаг", ge: "პირობითი სპარინგი ერთი ნაბიჯით" }, image: "images/yakusoku-ippon-kumite.jpg" },
    { japanese: "試し割り", transcription: { ru: "Тамеши-вари", ge: "ტამეში-ვარი" }, translation: { ru: "Разбивание предметов", ge: "ნივთების გატეხვა" }, image: "images/tameshiwari.jpg" },
    { japanese: "主審", transcription: { ru: "Шушин", ge: "შუშინი" }, translation: { ru: "Рефери", ge: "მსაჯი" }, image: "images/shushin.jpg" },
    { japanese: "呼吸法", transcription: { ru: "Кокю хо", ge: "კოკიუ ჰო" }, translation: { ru: "Дыхание", ge: "სუნთქვა" }, image: "images/kokyu-ho.jpg" },
    { japanese: "息吹", transcription: { ru: "Ибуки", ge: "იბუკი" }, translation: { ru: "Силовое дыхание", ge: "ძლიერი სუნთქვა" }, image: "images/ibuki.jpg" },
    { japanese: "野我", transcription: { ru: "Ногарэ", ge: "ნოგარე" }, translation: { ru: "Мягкое дыхание", ge: "რბილი სუნთქვა" }, image: "images/nogare.jpg" },
    { japanese: "押", transcription: { ru: "Осу", ge: "ოსუ" }, translation: { ru: "Приветствие, уважение", ge: "მისალმება, პატივისცემა" }, image: "images/osu.jpg" },
    { japanese: "級", transcription: { ru: "Кю", ge: "კიუ" }, translation: { ru: "Ученическая степень", ge: "მოსწავლის ხარისხი" }, image: "images/kyu.jpg" },
    { japanese: "段", transcription: { ru: "Дан", ge: "დანი" }, translation: { ru: "Мастерская степень", ge: "ოსტატის ხარისხი" }, image: "images/dan.jpg" },
    { japanese: "道着", transcription: { ru: "Доги", ge: "დოგი" }, translation: { ru: "Униформа, кимоно", ge: "ფორმა, კიმონო" }, image: "images/dogi.jpg" },
    { japanese: "巻藁", transcription: { ru: "Макивара", ge: "მაკივარა" }, translation: { ru: "Снаряд для ударов", ge: "დარტყმისთვის საშუალება" }, image: "images/makiwara.jpg" },
    { japanese: "さようなら", transcription: { ru: "Сайонара", ge: "საიონარა" }, translation: { ru: "До свидания", ge: "ნახვამდის" }, image: "images/sayonara.jpg" },
    { japanese: "正座", transcription: { ru: "Сэйза", ge: "სეიზა" }, translation: { ru: "Сидеть на коленях", ge: "მუხლებზე ჯდომა" }, image: "images/seiza.jpg" },
    { japanese: "安座", transcription: { ru: "Анза", ge: "ანზა" }, translation: { ru: "Сидеть по-турецки", ge: "ჯვარედინად ჯდომა" }, image: "images/anza.jpg" },
    { japanese: "黙想", transcription: { ru: "Мокусо", ge: "მოკუსო" }, translation: { ru: "Закрыть глаза", ge: "თვალების დახუჭვა" }, image: "images/mokuso.jpg" },
    { japanese: "黙想止め", transcription: { ru: "Мокусо ямэ", ge: "მოკუსო იამე" }, translation: { ru: "Открыть глаза", ge: "თვალების გახელა" }, image: "images/mokuso-yame.jpg" },
    { japanese: "神前礼", transcription: { ru: "Шинзен ни рэй", ge: "შინზენ ნი რეი" }, translation: { ru: "Поклон святыне", ge: "წმინდანისთვის მშვილდოსნობა" }, image: "images/shinzen-ni-rei.jpg" },
    { japanese: "先生に礼", transcription: { ru: "Сэнсэй ни рэй", ge: "სენსეი ნი რეი" }, translation: { ru: "Поклон учителю", ge: "მასწავლებლისთვის მშვილდოსნობა" }, image: "images/sensei-ni-rei.jpg" },
    { japanese: "お互いに礼", transcription: { ru: "Отагай ни рэй", ge: "ოტაგაი ნი რეი" }, translation: { ru: "Поклон друг другу", ge: "ერთმანეთისთვის მშვილდოსნობა" }, image: "images/otagai-ni-rei.jpg" },
    { japanese: "ありがとう", transcription: { ru: "Аригато", ge: "არიგატო" }, translation: { ru: "Спасибо", ge: "მადლობა" }, image: "images/arigato.jpg" },
    { japanese: "立てください", transcription: { ru: "Тате кудасай", ge: "ტატე კუდასაი" }, translation: { ru: "Встаньте пожалуйста", ge: "გთხოვთ წამოდგეთ" }, image: "images/tate-kudasai.jpg" },
    { japanese: "用意", transcription: { ru: "Йой", ge: "იოი" }, translation: { ru: "Приготовиться", ge: "მოემზადე" }, image: "images/yoi.jpg" },
    { japanese: "始め", transcription: { ru: "Хаджимэ", ge: "ჰაჯიმე" }, translation: { ru: "Начать", ge: "დაიწყე" }, image: "images/hajime.jpg" },
    { japanese: "止め", transcription: { ru: "Ямэ", ge: "იამე" }, translation: { ru: "Закончить", ge: "დაასრულე" }, image: "images/yame.jpg" },
    { japanese: "取ません", transcription: { ru: "Торимасен", ge: "ტორიმასენ" }, translation: { ru: "Не оценивается", ge: "არ შეფასდება" }, image: "images/torimasen.jpg" },
    { japanese: "引き分け", transcription: { ru: "Хикиваке", ge: "ჰიკივაკე" }, translation: { ru: "Ничья", ge: "ფრე" }, image: "images/hikiwake.jpg" },
    { japanese: "注意", transcription: { ru: "Чуй", ge: "ჩუი" }, translation: { ru: "Предупреждение", ge: "გაფრთხილება" }, image: "images/chui.jpg" },
    { japanese: "失格", transcription: { ru: "Сикаку", ge: "სიკაკუ" }, translation: { ru: "Дисквалификация", ge: "დისკვალიფიკაცია" }, image: "images/shikaku.jpg" },
    { japanese: "取り", transcription: { ru: "Тори", ge: "ტორი" }, translation: { ru: "Атакующий", ge: "შემტევი" }, image: "images/tori.jpg" },
    { japanese: "受け", transcription: { ru: "Уке", ge: "უკე" }, translation: { ru: "Защищающийся", ge: "მცველი" }, image: "images/uke.jpg" },
    { japanese: "回って", transcription: { ru: "Маватэ", ge: "მავატე" }, translation: { ru: "Повернуться", ge: "შემობრუნდი" }, image: "images/mawate.jpg" },
    { japanese: "反対", transcription: { ru: "Хантай", ge: "ჰანტაი" }, translation: { ru: "Смена", ge: "შეცვლა" }, image: "images/hantai.jpg" },
    { japanese: "直れ", transcription: { ru: "Наорэ", ge: "ნაორე" }, translation: { ru: "Вернуться в исходное положение", ge: "დაბრუნდი საწყის მდგომარეობაში" }, image: "images/naore.jpg" },
    { japanese: "休め", transcription: { ru: "Ясумэ", ge: "იასუმე" }, translation: { ru: "Расслабиться", ge: "დაისვენე" }, image: "images/yasume.jpg" },
    { japanese: "無我", transcription: { ru: "Мугорэ", ge: "მუგორე" }, translation: { ru: "Самостоятельно", ge: "დამოუკიდებლად" }, image: "images/mugore.jpg" },
    { japanese: "裏", transcription: { ru: "Ура", ge: "ურა" }, translation: { ru: "Обратная сторона", ge: "უკანა მხარე" }, image: "images/ura.jpg" },
    { japanese: "一", transcription: { ru: "Ичи", ge: "იჩი" }, translation: { ru: "1", ge: "1" }, image: "images/ichi.jpg" },
    { japanese: "二", transcription: { ru: "Ни", ge: "ნი" }, translation: { ru: "2", ge: "2" }, image: "images/ni.jpg" },
    { japanese: "三", transcription: { ru: "Сан", ge: "სან" }, translation: { ru: "3", ge: "3" }, image: "images/san.jpg" },
    { japanese: "四", transcription: { ru: "Ши (ён)", ge: "ში (იონ)" }, translation: { ru: "4", ge: "4" }, image: "images/shi.jpg" },
    { japanese: "五", transcription: { ru: "Го", ge: "გო" }, translation: { ru: "5", ge: "5" }, image: "images/go.jpg" },
    { japanese: "六", transcription: { ru: "Року", ge: "როკუ" }, translation: { ru: "6", ge: "6" }, image: "images/roku.jpg" },
    { japanese: "七", transcription: { ru: "Сичи", ge: "სიჩი" }, translation: { ru: "7", ge: "7" }, image: "images/shichi.jpg" },
    { japanese: "八", transcription: { ru: "Хачи", ge: "ჰაჩი" }, translation: { ru: "8", ge: "8" }, image: "images/hachi.jpg" },
    { japanese: "九", transcription: { ru: "Ку", ge: "კუ" }, translation: { ru: "9", ge: "9" }, image: "images/ku.jpg" },
    { japanese: "十", transcription: { ru: "Дзю", ge: "ძიუ" }, translation: { ru: "10", ge: "10" }, image: "images/ju.jpg" },
    { japanese: "平行足立", transcription: { ru: "Хэйсоку дачи", ge: "ჰეისოკუ დაჩი" }, translation: { ru: "Ступни вместе", ge: "ფეხები ერთად" }, image: "images/heisoku-dachi.jpg" },
    { japanese: "結び立", transcription: { ru: "Мусуби дачи", ge: "მუსუბი დაჩი" }, translation: { ru: "Пятки вместе, носки на 90°", ge: "ქუსლები ერთად, თითები 90°-ზე" }, image: "images/musubi-dachi.jpg" },
    { japanese: "平行立", transcription: { ru: "Хэйко дачи", ge: "ჰეიკო დაჩი" }, translation: { ru: "Ступни параллельно на ширине плеч", ge: "ფეხები პარალელურად მხრების სიგანეზე" }, image: "images/heiko-dachi.jpg" },
    { japanese: "自然立", transcription: { ru: "Шизен дачи", ge: "შიზენ დაჩი" }, translation: { ru: "Пятки на ширине плеч, носки развёрнуты", ge: "ქუსლები მხრების სიგანეზე, თითები გაშლილი" }, image: "images/shizen-dachi.jpg" },
    { japanese: "内八字立", transcription: { ru: "Учи хатидзи дачи", ge: "უჩი ჰატიძი დაჩი" }, translation: { ru: "Стойка голубя", ge: "მტრედის პოზა" }, image: "images/uchi-hachiji-dachi.jpg" },
    { japanese: "前屈立", transcription: { ru: "Зенкуцу дачи", ge: "ზენკუცუ დაჩი" }, translation: { ru: "Передняя стойка", ge: "წინა პოზა" }, image: "images/zenkutsu-dachi.jpg" },
    { japanese: "後屈立", transcription: { ru: "Кокуцу дачи", ge: "კოკუცუ დაჩი" }, translation: { ru: "Задняя стойка", ge: "უკანა პოზა" }, image: "images/kokutsu-dachi.jpg" },
    { japanese: "三戦立", transcription: { ru: "Санчин дачи", ge: "სანჩინ დაჩი" }, translation: { ru: "Стойка крепости", ge: "ციხის პოზა" }, image: "images/sanchin-dachi.jpg" },
    { japanese: "騎馬立", transcription: { ru: "Киба дачи", ge: "კიბა დაჩი" }, translation: { ru: "Стойка всадника", ge: "მხედრის პოზა" }, image: "images/kiba-dachi.jpg" },
    { japanese: "四股立", transcription: { ru: "Шико дачи", ge: "შიკო დაჩი" }, translation: { ru: "Стойка борца сумо", ge: "სუმოს მოჭიდავის პოზა" }, image: "images/shiko-dachi.jpg" },
    { japanese: "猫足立", transcription: { ru: "Некоаши дачи", ge: "ნეკოაში დაჩი" }, translation: { ru: "Стойка кота", ge: "კატის პოზა" }, image: "images/nekoashi-dachi.jpg" },
    { japanese: "鶴足立", transcription: { ru: "Цуроаши дачи", ge: "ცუროაში დაჩი" }, translation: { ru: "Стойка цапли", ge: "წეროს პოზა" }, image: "images/tsuruashi-dachi.jpg" },
    { japanese: "掛け足立", transcription: { ru: "Какэ аши дачи", ge: "კაკე აში დაჩი" }, translation: { ru: "Скрученная стойка", ge: "გადახვეული პოზა" }, image: "images/kake-ashi-dachi.jpg" },
    { japanese: "諸足立", transcription: { ru: "Мороаши дачи", ge: "მოროაში დაჩი" }, translation: { ru: "Ступни параллельно, одна впереди", ge: "ფეხები პარალელურად, ერთი წინ" }, image: "images/moroashi-dachi.jpg" },
    { japanese: "自由構え立", transcription: { ru: "Джиу камаетэ дачи", ge: "ძიუ კამაეტე დაჩი" }, translation: { ru: "Боевая стойка", ge: "საბრძოლო პოზა" }, image: "images/jiyu-kamaete-dachi.jpg" },
    { japanese: "上段", transcription: { ru: "Джодан", ge: "ჯოდანი" }, translation: { ru: "Верхний уровень", ge: "ზედა დონე" }, image: "images/jodan.jpg" },
    { japanese: "頭", transcription: { ru: "Агама", ge: "აგამა" }, translation: { ru: "Голова", ge: "თავი" }, image: "images/agama.jpg" },
    { japanese: "顎", transcription: { ru: "Аге", ge: "აგე" }, translation: { ru: "Подбородок", ge: "ნიკაპი" }, image: "images/age.jpg" },
    { japanese: "顔面", transcription: { ru: "Гаммен", ge: "გამმენი" }, translation: { ru: "Лицо", ge: "სახე" }, image: "images/gammen.jpg" },
    { japanese: "喉", transcription: { ru: "Нодо", ge: "ნოდო" }, translation: { ru: "Горло", ge: "ყელი" }, image: "images/nodo.jpg" },
    { japanese: "中段", transcription: { ru: "Чудан", ge: "ჩუდანი" }, translation: { ru: "Средний уровень", ge: "საშუალო დონე" }, image: "images/chudan.jpg" },
    { japanese: "胸", transcription: { ru: "Муне", ge: "მუნე" }, translation: { ru: "Грудь", ge: "მკერდი" }, image: "images/mune.jpg" },
    { japanese: "水落内", transcription: { ru: "Мизо-учи", ge: "მიზო-უჩი" }, translation: { ru: "Солнечное сплетение", ge: "მზის წნული" }, image: "images/mizo-uchi.jpg" },
    { japanese: "鎖骨", transcription: { ru: "Сакотцу", ge: "საკოტცუ" }, translation: { ru: "Ключица", ge: "ლავიწი" }, image: "images/sakotsu.jpg" },
    { japanese: "腹", transcription: { ru: "Хара", ge: "ჰარა" }, translation: { ru: "Живот", ge: "მუცელი" }, image: "images/hara.jpg" },
    { japanese: "脾臓", transcription: { ru: "Хизо", ge: "ჰიზო" }, translation: { ru: "Рёбра", ge: "ნეკნები" }, image: "images/hizo.jpg" },
    { japanese: "下段", transcription: { ru: "Гедан", ge: "გედანი" }, translation: { ru: "Нижний уровень", ge: "ქვედა დონე" }, image: "images/gedan.jpg" },
    { japanese: "腰", transcription: { ru: "Коши", ge: "კოში" }, translation: { ru: "Бёдра", ge: "ბარძაყები" }, image: "images/koshi.jpg" },
    { japanese: "追", transcription: { ru: "Ой", ge: "ოი" }, translation: { ru: "Одноимённое", ge: "ერთნაირი" }, image: "images/oi.jpg" },
    { japanese: "逆", transcription: { ru: "Гяку", ge: "გიაკუ" }, translation: { ru: "Разноимённое", ge: "სხვადასხვა" }, image: "images/gyaku.jpg" },
    { japanese: "左", transcription: { ru: "Хидари", ge: "ჰიდარი" }, translation: { ru: "Левая", ge: "მარცხენა" }, image: "images/hidari.jpg" },
    { japanese: "右", transcription: { ru: "Миги", ge: "მიგი" }, translation: { ru: "Правая", ge: "მარჯვენა" }, image: "images/migi.jpg" },
    { japanese: "上げ", transcription: { ru: "Аге", ge: "აგე" }, translation: { ru: "Вверх", ge: "ზევით" }, image: "images/age-direction.jpg" },
    { japanese: "横", transcription: { ru: "Ёко", ge: "იოკო" }, translation: { ru: "В сторону", ge: "გვერდზე" }, image: "images/yoko.jpg" },
    { japanese: "後ろ", transcription: { ru: "Уширо", ge: "უშირო" }, translation: { ru: "Назад", ge: "უკან" }, image: "images/ushiro.jpg" },
    { japanese: "前", transcription: { ru: "Мае", ge: "მაე" }, translation: { ru: "Вперёд", ge: "წინ" }, image: "images/mae.jpg" },
    { japanese: "回し", transcription: { ru: "Маваши", ge: "მავაში" }, translation: { ru: "Круговое", ge: "წრიული" }, image: "images/mawashi.jpg" },
    { japanese: "外", transcription: { ru: "Сото", ge: "სოტო" }, translation: { ru: "Внутрь", ge: "შიგნით" }, image: "images/soto.jpg" },
    { japanese: "内", transcription: { ru: "Учи", ge: "უჩი" }, translation: { ru: "Изнутри", ge: "შიგნიდან" }, image: "images/uchi.jpg" },
    { japanese: "降ろし", transcription: { ru: "Ороши", ge: "ოროში" }, translation: { ru: "Вниз", ge: "ქვევით" }, image: "images/oroshi.jpg" },
    { japanese: "正面", transcription: { ru: "Шомэн", ge: "შომენი" }, translation: { ru: "Движение вперёд", ge: "წინ მოძრაობა" }, image: "images/shomen.jpg" },
    { japanese: "下がり", transcription: { ru: "Сагари", ge: "საგარი" }, translation: { ru: "Движение назад", ge: "უკან მოძრაობა" }, image: "images/sagari.jpg" },
    { japanese: "正拳", transcription: { ru: "Сэйкэн", ge: "სეიკენი" }, translation: { ru: "Кулак (передняя часть)", ge: "მუშტი (წინა ნაწილი)" }, image: "images/seiken.jpg" },
    { japanese: "裏拳", transcription: { ru: "Уракэн", ge: "ურაკენი" }, translation: { ru: "Перевёрнутый кулак", ge: "გადაბრუნებული მუშტი" }, image: "images/uraken.jpg" },
    { japanese: "鉄槌", transcription: { ru: "Тэтсуи", ge: "ტეცუი" }, translation: { ru: "Кулак-молот", ge: "ჩაქუჩის მუშტი" }, image: "images/tetsui.jpg" },
    { japanese: "手刀", transcription: { ru: "Шуто", ge: "შუტო" }, translation: { ru: "Рука-нож", ge: "ხელი-დანა" }, image: "images/shuto.jpg" },
    { japanese: "背刀", transcription: { ru: "Хайто", ge: "ჰაიტო" }, translation: { ru: "Внутреннее ребро ладони", ge: "ხელის შიდა კიდე" }, image: "images/haito.jpg" },
    { japanese: "掌底", transcription: { ru: "Шотей", ge: "შოტეი" }, translation: { ru: "Пятка ладони", ge: "ხელის ქუსლი" }, image: "images/shotei.jpg" },
    { japanese: "弧拳", transcription: { ru: "Кокэн", ge: "კოკენი" }, translation: { ru: "Запястье", ge: "მაჯა" }, image: "images/koken.jpg" },
    { japanese: "熊手", transcription: { ru: "Кумадэ", ge: "კუმადე" }, translation: { ru: "Медвежья лапа", ge: "დათვის თათი" }, image: "images/kumade.jpg" },
    { japanese: "四本貫手", transcription: { ru: "Ёхон нукитэ", ge: "იოჰონ ნუკიტე" }, translation: { ru: "Рука-копьё", ge: "ხელი-შუბი" }, image: "images/yohon-nukite.jpg" },
    { japanese: "二本貫手", transcription: { ru: "Нихон нукитэ", ge: "ნიჰონ ნუკიტე" }, translation: { ru: "Рука-вилка", ge: "ხელი-ჩანგალი" }, image: "images/nihon-nukite.jpg" },
    { japanese: "中指一本拳", transcription: { ru: "Накаюби иппонкэн", ge: "ნაკაიუბი იპონკენი" }, translation: { ru: "Кулак со средним пальцем", ge: "მუშტი შუა თითით" }, image: "images/nakayubi-ipponken.jpg" },
    { japanese: "親指一本拳", transcription: { ru: "Ояюби иппонкэн", ge: "ოიაუბი იპონკენი" }, translation: { ru: "Кулак с большим пальцем", ge: "მუშტი დიდი თითით" }, image: "images/oyayubi-ipponken.jpg" },
    { japanese: "平拳", transcription: { ru: "Хиракэн", ge: "ჰირაკენი" }, translation: { ru: "Кулак с открытой ладонью", ge: "მუშტი ღია ხელით" }, image: "images/hiraken.jpg" },
    { japanese: "龍頭拳", transcription: { ru: "Рютокэн", ge: "რიუტოკენი" }, translation: { ru: "Кулак голова дракона", ge: "მუშტი დრაკონის თავი" }, image: "images/ryutoken.jpg" },
    { japanese: "背手", transcription: { ru: "Хайсю", ge: "ჰაიშუ" }, translation: { ru: "Тыльная сторона ладони", ge: "ხელის უკანა მხარე" }, image: "images/haishu.jpg" },
    { japanese: "刀峰", transcription: { ru: "Тохо", ge: "ტოჰო" }, translation: { ru: "Рука-крюк", ge: "ხელი-კაკალი" }, image: "images/toho.jpg" },
    { japanese: "鶏口", transcription: { ru: "Кейко", ge: "კეიკო" }, translation: { ru: "Рука-клюв", ge: "ხელი-ნისკარტი" }, image: "images/keiko.jpg" },
    { japanese: "小手", transcription: { ru: "Котэ", ge: "კოტე" }, translation: { ru: "Предплечье", ge: "წინამხარი" }, image: "images/kote.jpg" },
    { japanese: "肘", transcription: { ru: "Хиджи", ge: "ჰიძი" }, translation: { ru: "Локоть", ge: "იდაყვი" }, image: "images/hiji.jpg" },
    { japanese: "中足", transcription: { ru: "Тюсоку", ge: "ჩუსოკუ" }, translation: { ru: "Подушечка под пальцами стопы", ge: "ფეხის თითების ბალიში" }, image: "images/chusoku.jpg" },
    { japanese: "足刀", transcription: { ru: "Сокуто", ge: "სოკუტო" }, translation: { ru: "Нога-нож", ge: "ფეხი-დანა" }, image: "images/sokuto.jpg" },
    { japanese: "底足", transcription: { ru: "Тэйсоку", ge: "ტეისოკუ" }, translation: { ru: "Внутренняя выемка стопы", ge: "ფეხის შიდა ღრუ" }, image: "images/teisoku.jpg" },
    { japanese: "平足", transcription: { ru: "Хэйсоку", ge: "ჰეისოკუ" }, translation: { ru: "Подъём стопы", ge: "ფეხის ზურგი" }, image: "images/heisoku.jpg" },
    { japanese: "足", transcription: { ru: "Аши", ge: "აში" }, translation: { ru: "Подошва", ge: "ფეხის ძირი" }, image: "images/ashi.jpg" },
    { japanese: "踵", transcription: { ru: "Какато", ge: "კაკატო" }, translation: { ru: "Пятка", ge: "ქუსლი" }, image: "images/kakato.jpg" },
    { japanese: "脛", transcription: { ru: "Сунэ", ge: "სუნე" }, translation: { ru: "Голень", ge: "წვივი" }, image: "images/sune.jpg" },
    { japanese: "膝", transcription: { ru: "Хидза", ge: "ჰიძა" }, translation: { ru: "Колено", ge: "მუხლი" }, image: "images/hiza.jpg" },
    { japanese: "正拳突き", transcription: { ru: "Сэйкэн цуки", ge: "სეიკენ ცუკი" }, translation: { ru: "Прямой удар кулаком", ge: "პირდაპირი დარტყმა მუშტით" }, image: "images/seiken-tsuki.jpg" },
    { japanese: "縦突き", transcription: { ru: "Татэ-цуки", ge: "ტატე-ცუკი" }, translation: { ru: "Удар кулаком вертикально", ge: "ვერტიკალური დარტყმა მუშტით" }, image: "images/tate-tsuki.jpg" },
    { japanese: "鉤突き", transcription: { ru: "Лго-цуки", ge: "ლგო-ცუკი" }, translation: { ru: "Удар крюком снизу вверх", ge: "კაკლის დარტყმა ქვევით-ზევით" }, image: "images/lgo-tsuki.jpg" },
    { japanese: "正拳顎打ち", transcription: { ru: "Сэйкэн аго-учи", ge: "სეიკენ აგო-უჩი" }, translation: { ru: "Секущий удар кулаком в голову", ge: "მჭრელი დარტყმა თავში" }, image: "images/seiken-ago-uchi.jpg" },
    { japanese: "下突き", transcription: { ru: "Шита-цуки", ge: "შიტა-ცუკი" }, translation: { ru: "Удар в корпус перевернутым кулаком", ge: "დარტყმა ტანში გადაბრუნებული მუშტით" }, image: "images/shita-tsuki.jpg" },
    { japanese: "諸手突き", transcription: { ru: "Моротэ-цуки", ge: "მოროტე-ცუკი" }, translation: { ru: "Удар двумя руками", ge: "დარტყმა ორი ხელით" }, image: "images/morote-tsuki.jpg" },
    { japanese: "山突き", transcription: { ru: "Яма-цуки", ge: "იამა-ცუკი" }, translation: { ru: "Удар двумя руками на разных уровнях", ge: "დარტყმა ორი ხელით სხვადასხვა დონეზე" }, image: "images/yama-tsuki.jpg" },
    { japanese: "順突き", transcription: { ru: "Дзюн-цуки", ge: "ძიუნ-ცუკი" }, translation: { ru: "Удар в сторону", ge: "დარტყმა გვერდზე" }, image: "images/jun-tsuki.jpg" },
    { japanese: "掌底打ち", transcription: { ru: "Шотэй-учи", ge: "შოტეი-უჩი" }, translation: { ru: "Удар пяткой ладони", ge: "დარტყმა ხელის ქუსლით" }, image: "images/shotei-uchi.jpg" },
    { japanese: "四本貫手打ち", transcription: { ru: "Ёхон нукитэ", ge: "იოჰონ ნუკიტე" }, translation: { ru: "Удар копьём", ge: "დარტყმა შუბით" }, image: "images/yohon-nukite-uchi.jpg" },
    { japanese: "鉄槌込髪打ち", transcription: { ru: "Тетсуи коми ками-учи", ge: "ტეცუი კომი კამი-უჩი" }, translation: { ru: "Удар молотом сбоку по голове", ge: "ჩაქუჩის დარტყმა თავში გვერდიდან" }, image: "images/tetsui-komi-kami-uchi.jpg" },
    { japanese: "鉄槌降ろし顔面打ち", transcription: { ru: "Тетсуи ороши гаммен-учи", ge: "ტეცუი ოროში გამმენ-უჩი" }, translation: { ru: "Удар молотом сверху по голове", ge: "ჩაქუჩის დარტყმა თავში ზევიდან" }, image: "images/tetsui-oroshi-gammen-uchi.jpg" },
    { japanese: "鉄槌脾臓打ち", transcription: { ru: "Тетсуи хизо-учи", ge: "ტეცუი ჰიზო-უჩი" }, translation: { ru: "Удар молотом по рёбрам", ge: "ჩაქუჩის დარტყმა ნეკნებში" }, image: "images/tetsui-hizo-uchi.jpg" },
    { japanese: "鉄槌横打ち", transcription: { ru: "Тетсуи ёко-учи", ge: "ტეცუი იოკო-უჩი" }, translation: { ru: "Удар молотом в сторону", ge: "ჩაქუჩის დარტყმა გვერდზე" }, image: "images/tetsui-yoko-uchi.jpg" },
    { japanese: "裏拳正面打ち", transcription: { ru: "Уракэн шомен-учи", ge: "ურაკენ შომენ-უჩი" }, translation: { ru: "Удар перевёрнутым кулаком вперёд в лицо", ge: "დარტყმა გადაბრუნებული მუშტით სახეში" }, image: "images/uraken-shomen-uchi.jpg" },
    { japanese: "裏拳左右打ち", transcription: { ru: "Уракэн саю-учи", ge: "ურაკენ საიუ-უჩი" }, translation: { ru: "Удар перевёрнутым кулаком в сторону сверху", ge: "დარტყმა გადაბრუნებული მუშტით გვერდზე ზევიდან" }, image: "images/uraken-sayu-uchi.jpg" },
    { japanese: "裏拳脾臓打ち", transcription: { ru: "Уракэн хизо-учи", ge: "ურაკენ ჰიზო-უჩი" }, translation: { ru: "Удар перевёрнутым кулаком по рёбрам", ge: "დარტყმა გადაბრუნებული მუშტით ნეკნებში" }, image: "images/uraken-hizo-uchi.jpg" },
    { japanese: "裏拳回し打ち", transcription: { ru: "Уракэн маваши-учи", ge: "ურაკენ მავაში-უჩი" }, translation: { ru: "Круговой удар перевёрнутым кулаком", ge: "წრიული დარტყმა გადაბრუნებული მუშტით" }, image: "images/uraken-mawashi-uchi.jpg" },
    { japanese: "手刀横顔面打ち", transcription: { ru: "Шуто йоко гаммен-учи", ge: "შუტო იოკო გამმენ-უჩი" }, translation: { ru: "Удар ребром ладони по голове", ge: "დარტყმა ხელის კიდით თავში" }, image: "images/shuto-yoko-gammen-uchi.jpg" },
    { japanese: "手刀鎖骨打ち", transcription: { ru: "Шуто сакоцу-учи", ge: "შუტო საკოტცუ-უჩი" }, translation: { ru: "Удар ребром ладони по ключице", ge: "დარტყმა ხელის კიდით ლავიწში" }, image: "images/shuto-sakotsu-uchi.jpg" },
    { japanese: "手刀鎖骨打ち込み", transcription: { ru: "Шуто сакоцу-учи коми", ge: "შუტო საკოტცუ-უჩი კომი" }, translation: { ru: "Прямой удар ребром ладони в ключицу", ge: "პირდაპირი დარტყმა ხელის კიდით ლავიწში" }, image: "images/shuto-sakotsu-uchi-komi.jpg" },
    { japanese: "手刀上段内打ち", transcription: { ru: "Шуто джодан учи-учи", ge: "შუტო ჯოდან უჩი-უჩი" }, translation: { ru: "Удар ребром ладони изнутри в голову", ge: "დარტყმა ხელის კიდით შიგნიდან თავში" }, image: "images/shuto-jodan-uchi-uchi.jpg" },
    { japanese: "手刀脾臓打ち", transcription: { ru: "Шуто хизо-учи", ge: "შუტო ჰიზო-უჩი" }, translation: { ru: "Удар ребром ладони по рёбрам", ge: "დარტყმა ხელის კიდით ნეკნებში" }, image: "images/shuto-hizo-uchi.jpg" },
    { japanese: "正拳回し打ち", transcription: { ru: "Сейкен маваши-учи", ge: "სეიკენ მავაში-უჩი" }, translation: { ru: "Удар крюком сбоку", ge: "კაკლის დარტყმა გვერდიდან" }, image: "images/seiken-mawashi-uchi.jpg" },
    { japanese: "前肘当て", transcription: { ru: "Мае хиджи атэ", ge: "მაე ჰიძი ატე" }, translation: { ru: "Удар локтем вперёд сбоку", ge: "დარტყმა იდაყვით წინ გვერდიდან" }, image: "images/mae-hiji-ate.jpg" },
    { japanese: "上げ肘当て", transcription: { ru: "Аге хиджи атэ", ge: "აგე ჰიძი ატე" }, translation: { ru: "Удар локтем снизу в подбородок", ge: "დარტყმა იდაყვით ქვევიდან ნიკაპში" }, image: "images/age-hiji-ate.jpg" },
    { japanese: "降ろし肘当て", transcription: { ru: "Ороши хиджи атэ", ge: "ოროში ჰიძი ატე" }, translation: { ru: "Удар локтем сверху вниз", ge: "დარტყმა იდაყვით ზევიდან ქვევით" }, image: "images/oroshi-hiji-ate.jpg" },
    { japanese: "横肘当て", transcription: { ru: "Ёко хиджи атэ", ge: "იოკო ჰიძი ატე" }, translation: { ru: "Удар локтем в сторону", ge: "დარტყმა იდაყვით გვერდზე" }, image: "images/yoko-hiji-ate.jpg" },
    { japanese: "後ろ肘当て", transcription: { ru: "Уширо хиджи атэ", ge: "უშირო ჰიძი ატე" }, translation: { ru: "Удар локтем назад", ge: "დარტყმა იდაყვით უკან" }, image: "images/ushiro-hiji-ate.jpg" },
    { japanese: "正拳上段受け", transcription: { ru: "Сэйкэн джодан-укэ", ge: "სეიკენ ჯოდან-უკე" }, translation: { ru: "Верхний блок предплечьем", ge: "ზედა ბლოკი წინამხრით" }, image: "images/seiken-jodan-uke.jpg" },
    { japanese: "正拳中段外受け", transcription: { ru: "Сэйкэн чудан сото-укэ", ge: "სეიკენ ჩუდან სოტო-უკე" }, translation: { ru: "Блок снаружи внутрь предплечьем", ge: "ბლოკი გარედან შიგნით წინამხრით" }, image: "images/seiken-chudan-soto-uke.jpg" },
    { japanese: "正拳中段内受け", transcription: { ru: "Сэйкэн чудан учи-укэ", ge: "სეიკენ ჩუდან უჩი-უკე" }, translation: { ru: "Блок изнутри наружу предплечьем", ge: "ბლოკი შიგნიდან გარეთ წინამხრით" }, image: "images/seiken-chudan-uchi-uke.jpg" },
    { japanese: "正拳前下段払い", transcription: { ru: "Сэйкэн мая гедан-барай", ge: "სეიკენ მაია გედან-ბარაი" }, translation: { ru: "Нижний блок предплечьем вперёд", ge: "ქვედა ბლოკი წინამხრით წინ" }, image: "images/seiken-mae-gedan-barai.jpg" },
    { japanese: "回し下段払い", transcription: { ru: "Маваши гедан-барай", ge: "მავაში გედან-ბარაი" }, translation: { ru: "Нижний круговой блок предплечьем", ge: "ქვედა წრიული ბლოკი წინამხრით" }, image: "images/mawashi-gedan-barai.jpg" },
    { japanese: "諸手受け", transcription: { ru: "Моротэ-укэ", ge: "მოროტე-უკე" }, translation: { ru: "Блок усиленный второй рукой", ge: "ბლოკი გაძლიერებული მეორე ხელით" }, image: "images/morote-uke.jpg" },
    { japanese: "諸手中段内受け", transcription: { ru: "Моротэ чудан учи-укэ", ge: "მოროტე ჩუდან უჩი-უკე" }, translation: { ru: "Двойной разводящий блок предплечьями", ge: "ორმაგი გამყოფი ბლოკი წინამხრებით" }, image: "images/morote-chudan-uchi-uke.jpg" },
    { japanese: "中段内受け/下段払い", transcription: { ru: "Чудан учи-укэ/гедан-барай", ge: "ჩუდან უჩი-უკე/გედან-ბარაი" }, translation: { ru: "Двойной блок на среднем и нижнем уровнях", ge: "ორმაგი ბლოკი საშუალო და ქვედა დონეზე" }, image: "images/chudan-uchi-uke-gedan-barai.jpg" },
    { japanese: "手刀回し受け", transcription: { ru: "Шуто маваши-укэ", ge: "შუტო მავაში-უკე" }, translation: { ru: "Круговой блок двумя руками", ge: "წრიული ბლოკი ორი ხელით" }, image: "images/shuto-mawashi-uke.jpg" },
    { japanese: "正拳十字受け", transcription: { ru: "Сэйкэн джуджи-укэ", ge: "სეიკენ ჯუჯი-უკე" }, translation: { ru: "Скрестный блок предплечьями", ge: "ჯვარედინი ბლოკი წინამხრებით" }, image: "images/seiken-juji-uke.jpg" },
    { japanese: "掌底受け", transcription: { ru: "Шотэй-укэ", ge: "შოტეი-უკე" }, translation: { ru: "Блок пяткой ладони", ge: "ბლოკი ხელის ქუსლით" }, image: "images/shotei-uke.jpg" },
    { japanese: "手刀中段外受け", transcription: { ru: "Шуто чудан сото-укэ", ge: "შუტო ჩუდან სოტო-უკე" }, translation: { ru: "Блок ребром ладони снаружи", ge: "ბლოკი ხელის კიდით გარედან" }, image: "images/shuto-chudan-soto-uke.jpg" },
    { japanese: "押さえ受け", transcription: { ru: "Осаи-укэ", ge: "ოსაი-უკე" }, translation: { ru: "Блок-накладка ладонью", ge: "ბლოკი ხელის გადაფარვით" }, image: "images/osai-uke.jpg" },
    { japanese: "脛受け", transcription: { ru: "Сунэ-укэ", ge: "სუნე-უკე" }, translation: { ru: "Блок голенью", ge: "ბლოკი წვივით" }, image: "images/sune-uke.jpg" },
    { japanese: "膝受け", transcription: { ru: "Хидза-укэ", ge: "ჰიძა-უკე" }, translation: { ru: "Блок коленом", ge: "ბლოკი მუხლით" }, image: "images/hiza-uke.jpg" }
];
